### ISSUE TITLE
NPM package is not up-to-date

### ISSUE THREAD

**Issue by Bobakanoosh** [vutran6853/vue3-chart-v2#6]
Patch #3 does not install when installing the package via `npm i vue3-chart-v2`.

**Comment by vutran6853** [comment]
Thank for the report. I update npm package to 0.8.2 to stay to update. Let me know if there any issue.

**Comment by vutran6853** [comment]
Close issue since npm package is update from preview comments

**Comment by Pr0ny** [comment]
Re-opening the issue because npm package is not up to date. Since #14 has been accepted, can we have the 0.8.3 on NPM, so we could update our project dependancies ?
